server:
    port: 9086
    servlet:
        contextPath: /products
      
management:
    endpoint:
        refresh:
            enabled: true
    endpoints:
        web:
            exposure:
                include: prometheus, health, info, metrics, refresh, loggers
    health:
        solr:
            enabled: false
 
search:
    pagination:
        size:
            limit: 70
